//Authentication 

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOGOUT='LOGOUT';
export const GET_USERDATASUCCESS = 'GET_USERDATASUCCESS';
export const GET_USERDATAFAILED = 'GET_USERDATAFAILED';

//Companies

export const GET_COMPANIES_SUCCESS = 'GET_COMPANIES_SUCCESS'
export const GET_COMPANIES_FAILED = 'GET_COMPANIES_FAILED'
export const GET_COMPANIES_START = 'GET_COMPANIES_START'
export const COMPANIES_SORT = 'COMPANIES_SORT'
export const COMPANY_DELETE_SUCCESS ='COMPANY_DELETE_SUCCESS'
export const COMPANY_DELETE_FAIL = 'COMPANY_DELETE_FAILED'

//Companies 

export const ON_APPLY_START='ON_APPLY_START'
export const ON_APPLY_SUCCESS = 'ON_APPLY_SUCCESS'
export const ON_APPLY_FAILED = 'ON_APPLY_FAILED'
export const ON_WITHDRAW_START = 'ON_WITHDRAW_START'
export const ON_WITHDRAW_SUCCESS='ON_WITHDRAW_SUCCESS'
export const ON_WITHDRAW_FAILED ='ON_WITHDRAW_FAILED'

